"""Circuit manipulation module for Skadi.

This module provides tools for manipulating, transforming, optimizing,
and analyzing quantum circuits generated by Skadi.

Core Components:
    - CircuitTransformer: Apply PennyLane transforms to circuits
    - CircuitOptimizer: Optimize circuits for depth and gate count
    - CircuitAnalyzer: Analyze circuit structure and generate explanations
    - CircuitRewriter: Modify circuits using natural language requests
"""

from skadi.manipulation.analyzer import CircuitAnalyzer
from skadi.manipulation.optimizer import CircuitOptimizer
from skadi.manipulation.rewriter import CircuitRewriter
from skadi.manipulation.transformer import CircuitTransformer

__all__ = [
    "CircuitTransformer",
    "CircuitOptimizer",
    "CircuitAnalyzer",
    "CircuitRewriter",
]
